import { type AppCode, APP_CODE } from "../share/code"

const backendCodeMapping: Readonly<Record<string, AppCode>> = {
  // Login
  AUTH_LOGIN_SUCCESS: APP_CODE.AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAIL: APP_CODE.AUTH_LOGIN_FAIL,
  AUTH_LOGIN_VALIDATION_ERROR: APP_CODE.AUTH_LOGIN_VALIDATION_ERROR,
  AUTH_INVALID_CREDENTIALS: APP_CODE.AUTH_INVALID_CREDENTIALS,
  NOT_VERIFIED: APP_CODE.NOT_VERIFIED,

  // Register & User
  REGISTER_SUCCESS: APP_CODE.REGISTER_SUCCESS,
  USER_ALREADY_EXISTS: APP_CODE.USER_ALREADY_EXISTS,
  USER_NOT_FOUND: APP_CODE.USER_NOT_FOUND,
  USER_NOT_VERIFY: APP_CODE.USER_NOT_VERIFY,
  VALIDATION_FAILED: APP_CODE.VALIDATION_FAILED,

  // Verify Account
  SENT_VERIFY: APP_CODE.SENT_VERIFY,
  VERIFY_SUCCESS: APP_CODE.VERIFY_SUCCESS,
  USER_VERIFIED_BEFORE: APP_CODE.USER_VERIFIED_BEFORE,
  VERIFY_CODE_NOT_MATCHED: APP_CODE.VERIFY_CODE_NOT_MATCHED,
  VERIFY_CODE_EXPIRED: APP_CODE.VERIFY_CODE_EXPIRED,
  TOO_MANY_VERIFY_ATTEMPTS: APP_CODE.TOO_MANY_VERIFY_ATTEMPTS,
  EXPIRED: APP_CODE.EXPIRED,

  // Forgot Password
  USER_REQUEST_FORGOT_NOT_VERIFIED: APP_CODE.USER_REQUEST_FORGOT_NOT_VERIFIED,
  FORGOT_PASSWORD_CODE_SENT: APP_CODE.FORGOT_PASSWORD_CODE_SENT,
  PASSWORD_CHANGED: APP_CODE.PASSWORD_CHANGED,
  FORGOT_PASSWORD_VERIFY_CODE_NOT_MATCHED: APP_CODE.FORGOT_PASSWORD_VERIFY_CODE_NOT_MATCHED,
  FORGOT_PASSWORD_VERIFY_CODE_EXPIRED: APP_CODE.FORGOT_PASSWORD_VERIFY_CODE_EXPIRED,
  FORGOT_PASSWORD_TOO_MANY_VERIFY_ATTEMPTS: APP_CODE.FORGOT_PASSWORD_TOO_MANY_VERIFY_ATTEMPTS,
  EMAIL_NOT_FOUND: APP_CODE.EMAIL_NOT_FOUND,

  // Resend Verification Code
  VERIFICATION_CODE_RESENT: APP_CODE.VERIFICATION_CODE_RESENT,
  CAN_NOT_RESEND_CODE_FOR_VERIFIED_ACCOUNT: APP_CODE.CAN_NOT_RESEND_CODE_FOR_VERIFIED_ACCOUNT,
  RESEND_REQUEST_IS_LIMITED_BY_1M: APP_CODE.RESEND_REQUEST_IS_LIMITED_BY_1M,
  RESEND_CODE_EXPIRED: APP_CODE.RESEND_CODE_EXPIRED,
  RESEND_CODE_TOO_MANY_REQUESTS: APP_CODE.RESEND_CODE_TOO_MANY_REQUESTS,

  // Authorization / Token
  AUTH_UNAUTHORIZED: APP_CODE.AUTH_UNAUTHORIZED,
  AUTH_TOKEN_EXPIRED: APP_CODE.AUTH_TOKEN_EXPIRED,
  AUTH_INVALID_TOKEN: APP_CODE.AUTH_INVALID_TOKEN,

  // Network & System Errors
  BAD_REQUEST: APP_CODE.BAD_REQUEST,
  BAD_RESPONSE: APP_CODE.BAD_RESPONSE,
  CANCELED: APP_CODE.CANCELED,
  INVALID_CONFIG: APP_CODE.INVALID_CONFIG,
  NETWORK_ERROR: APP_CODE.NETWORK_ERROR,
  TIMEOUT: APP_CODE.TIMEOUT,
  TOO_MANY_REDIRECTS: APP_CODE.TOO_MANY_REDIRECTS,
  UNKNOWN_ERROR: APP_CODE.UNKNOWN_ERROR,
  UNKNOWN: APP_CODE.UNKNOWN,
}

export const normalizeBackendCode = (code?: string): AppCode => {
  if (!code) return APP_CODE.UNKNOWN
  if (backendCodeMapping[code]) return backendCodeMapping[code]

  console.error(`${code} doesn't have in backend code mapping`)
  return APP_CODE.UNKNOWN
}