export type AppCode = (typeof APP_CODE)[keyof typeof APP_CODE]

export const APP_CODE = {
  // Login
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAIL: "AUTH_LOGIN_FAIL",
  AUTH_LOGIN_VALIDATION_ERROR: "AUTH_LOGIN_VALIDATION_ERROR",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  NOT_VERIFIED: "NOT_VERIFIED",

  // Register & User
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_NOT_VERIFY: "USER_NOT_VERIFY",
  USER_NOT_VERIFIED: "USER_NOT_VERIFIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",

  // Verify Account
  SENT_VERIFY: "SENT_VERIFY",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  USER_VERIFIED_BEFORE: "USER_VERIFIED_BEFORE",
  VERIFY_CODE_NOT_MATCHED: "VERIFY_CODE_NOT_MATCHED",
  VERIFY_CODE_EXPIRED: "VERIFY_CODE_EXPIRED",
  TOO_MANY_VERIFY_ATTEMPTS: "TOO_MANY_VERIFY_ATTEMPTS",
  EXPIRED: "EXPIRED",

  // Forgot Password
  USER_REQUEST_FORGOT_NOT_VERIFIED: "USER_REQUEST_FORGOT_NOT_VERIFIED",
  FORGOT_PASSWORD_CODE_SENT: "FORGOT_PASSWORD_CODE_SENT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  FORGOT_PASSWORD_VERIFY_CODE_NOT_MATCHED: "FORGOT_PASSWORD_VERIFY_CODE_NOT_MATCHED",
  FORGOT_PASSWORD_VERIFY_CODE_EXPIRED: "FORGOT_PASSWORD_VERIFY_CODE_EXPIRED",
  FORGOT_PASSWORD_TOO_MANY_VERIFY_ATTEMPTS: "FORGOT_PASSWORD_TOO_MANY_VERIFY_ATTEMPTS",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",

  // Resend Verification Code
  VERIFICATION_CODE_RESENT: "VERIFICATION_CODE_RESENT",
  CAN_NOT_RESEND_CODE_FOR_VERIFIED_ACCOUNT: "CAN_NOT_RESEND_CODE_FOR_VERIFIED_ACCOUNT",
  RESEND_REQUEST_IS_LIMITED_BY_1M: "RESEND_REQUEST_IS_LIMITED_BY_1M",
  RESEND_CODE_EXPIRED: "RESEND_CODE_EXPIRED",
  RESEND_CODE_TOO_MANY_REQUESTS: "RESEND_CODE_TOO_MANY_REQUESTS",

  // Authorization / Token
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",

  // Network & System Errors
  BAD_REQUEST: "BAD_REQUEST",
  BAD_RESPONSE: "BAD_RESPONSE",
  CANCELED: "CANCELED",
  INVALID_CONFIG: "INVALID_CONFIG",
  NETWORK_ERROR: "NETWORK_ERROR",
  TIMEOUT: "TIMEOUT",
  TOO_MANY_REDIRECTS: "TOO_MANY_REDIRECTS",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  UNKNOWN: "UNKNOWN",
} as const