spring.application.name=focusflow
spring.datasource.url = jdbc:postgresql://localhost:5432/focusflow
spring.datasource.username = postgres
spring.datasource.password= 000000

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
jwt.secret=minecraftisthebestgameeverandthisisaverylongsecretkey
jwt.access-expiration=3600000
jwt.refresh-expiration=1